---
- name: Software | Utilities | Install
  yum:
    state: present
    name:
      - bat
      - nmap
      - curl
      - htop
      - tmux
      - lsof
      - neofetch
      - tldr
      - strongswan
      - openldap-clients
      - sssd-tools
      - httpie
      - jq
      - podman
      - kernel-tools
      - ncdu
      - glances
      - bpytop
      - fail2ban
  when: ansible_os_family == "RedHat"
