---
- name: User | add user bpfoley
  include_tasks: users/bpfoley.yml

- block:
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_utilities.yml
  #- import_tasks: software/packages_pip.yml
